[package]
name = "django-query"
version = "0.1.0"
authors = ["Edmund Smith <ed.smith@collabora.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[workspace]

[dependencies]
anyhow = "1"
derive-queryable = { path="derive-queryable" }
thiserror = "1.0"
