[package]
name = "django-query"
version = "0.1.0"
authors = ["Edmund Smith <ed.smith@collabora.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
thiserror = "1.0"
django_derive= { path="../django_derive" }
chrono = "0.4"
serde_json = "1"
wiremock = { version="0.5", optional=true }
strum = { version = "0.21", option=true }

[features]
default = [ "mock" ]
mock = [ "wiremock"  ]
