[package]
name = "test_suite"
version = "0.1.0"
edition = "2021"
authors = ["Ed Smith <ed.smith@collabora.com>"]
publish = false
license = "Apache-2.0 OR MIT"

[dependencies]
django-query = { path = "../django-query" }
serde_json = "1"